title: Blog do Willian
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
#url: "https://wteophilo.github.io/"
url: "http://localhost:4000/"

# Author Settings
author: Willian Teophilo
# add your photo
author-img: wteophilo.jpg 
# add description
about-author: Sempre em busca de algo novo para aprender.
# add your Twitter handle
social-twitter: wilteophilo 
# add your github handle
social-github: wteophilo
# add your linkedin handle
social-linkedin: wteophilo
social-email: wteophilo@gmail.com

# Disqus
discus-identifier: wteophilo-github-io

# Tracker
analytics: UA-116553793-1

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 5
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
