title: Willian Teophilo
description: Willian Teophilo
url: "https://wteophilo.github.io/"
# Author Settings
author: Willian Teophilo
# add your photo
author-img: wteophilo.jpg 
# add description
about-author: Sempre em busca de algo novo para aprender.
# add your Twitter handle
social-twitter: wilteophilo 
# add your github handle
social-github: wteophilo
# add your linkedin handle
social-linkedin: wteophilo
social-email: wteophilo@gmail.com

# Disqus
discus-identifier: wteophilo-github-io

# Tracker
analytics: UA-116553793-1

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji
  - jekyll-seo-tag
  - jekyll-feed

paginate: 5
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
