version: "3.2"

services:
  web:
    tty: true
    stdin_open: true
    image: blog_will
    build:
      context: .
    volumes:
      - ".:/app"
    container_name: blog_will
    expose:
      - 4000