version: "3.2"

services:
  web:
    tty: true
    stdin_open: true
    environment:
      - JEKYLL_ENV=docker
    image: blog_will
    build:
      context: .
    volumes:
      - ".:/app"
    container_name: blog_will
    ports:
      - 4000:4000